apiVersion: "captainjustin.space/v1"
kind: CronScale
metadata:
  name: scale-down
spec:
  cronSpec: "*/4 * * * *"
  scaleTargetRef:
    apiVersion: "extensions/v1beta1"
    kind: "deployment"
    name: "worker"
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
---
apiVersion: "captainjustin.space/v1"
kind: CronScale
metadata:
  name: scale-up
spec:
  cronSpec: "*/3 * * * *"
  scaleTargetRef:
    apiVersion: "extensions/v1beta1"
    kind: "deployment"
    name: "worker"
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 40