apiVersion: "captainjustin.space/v1"
kind: CronScale
metadata:
  name: scale-down-6pm
spec:
  cronSpec: "18 * * * *"
  scaleTargetRef:
    apiVersion: "extensions/v1beta1"
    kind: "deployment"
    name: "worker"
  HorizontalPodAutoScaler:
    name: "worker"
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60
---
apiVersion: "captainjustin.space/v1"
kind: CronScale
metadata:
  name: scale-up-9am
spec:
  cronSpec: "9 * * * *"
  scaleTargetRef:
    apiVersion: "extensions/v1beta1"
    kind: "deployment"
    name: "worker"
  HorizontalPodAutoScaler:
    name: "worker"
    minReplicas: 4
    maxReplicas: 8
    targetCPUUtilizationPercentage: 40
