apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cronhpas.kubernetes-misc.xyz
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kubernetes-misc.xyz
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cronhpas
    # singular name to be used as an alias on the CLI and for display
    singular: cronhpa
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronHPA
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ch
      - chpa
  #  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            cronSpec:
              type: string
            cronSpecSeconds:
              type: string
            scaleTargetRef:
              type: object
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
            horizontalPodAutoScaler:
              type: object
              properties:
                name:
                  type: string
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
                targetCPUUtilizationPercentage:
                  type: integer
